server:
  port: 8907

mybatis:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.example.core.api.repository
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.52.208.123:3306/master0?useServerPrepStmts=true&cachePrepStmts=true
    password: root
    username: root

