server:
  port: 8905

mybatis:
  mapper-locations: classpath:mappers/*.xml
  typeAliasesPackage: com.sharding.druid.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  shardingsphere:
    datasource:
      names: mydb
      # 配置主库
      mydb:
        url: jdbc:mysql://106.52.208.123:3306/master0?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=Hongkong
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 123456
        #最大连接数
        maxPoolSize: 20
    props:
      sql.show: true # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！

    sharding:
      #分表策略
      tables:
        student_score:
          #真实表分布
          actual-data-nodes: mydb.student_score_$->{0..2}
          table-strategy:
            #内置分表策略
            inline:
              sharding-column: student_id
              algorithm-expression: student_score_$->{student_id % 3}
          key-generator:
            column: order_id
            type: SNOWFLAKE